-- Script SQL para crear tablas del módulo de proveedores
-- Database: conectae_conectaerpbd

-- Tabla: proveedores (tabla principal)
CREATE TABLE IF NOT EXISTS `proveedores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL UNIQUE,
  `tipo_proveedor` ENUM('BIENES','SERVICIOS','AMBOS') DEFAULT 'BIENES',
  `razon_social` VARCHAR(200) NOT NULL,
  `nombre_comercial` VARCHAR(200) DEFAULT NULL,
  `rut` VARCHAR(20) NOT NULL UNIQUE,
  `giro` VARCHAR(200) DEFAULT NULL,
  `categoria` ENUM('ESTRATEGICO','PREFERENTE','HOMOLOGADO','OCASIONAL') DEFAULT 'HOMOLOGADO',
  `clasificacion_abc` ENUM('A','B','C') DEFAULT 'C',
  `pais_origen` VARCHAR(100) DEFAULT 'Chile',
  `representante_legal` VARCHAR(200) DEFAULT NULL,
  `ejecutivo_asignado` VARCHAR(100) DEFAULT NULL,
  `idioma` VARCHAR(50) DEFAULT 'Español',
  `incoterm_preferido` VARCHAR(20) DEFAULT NULL,
  `condicion_pago` VARCHAR(100) DEFAULT NULL,
  `plazo_pago_dias` INT(11) DEFAULT 30,
  `forma_pago` VARCHAR(100) DEFAULT NULL,
  `descuento_pronto_pago` DECIMAL(5,2) DEFAULT 0.00,
  `moneda_transaccion` VARCHAR(10) DEFAULT 'CLP',
  `metodo_envio` VARCHAR(100) DEFAULT NULL,
  `plazo_entrega_dias` INT(11) DEFAULT NULL,
  `calificacion` DECIMAL(3,2) DEFAULT 0.00,
  `fecha_ultima_evaluacion` DATE DEFAULT NULL,
  `tipo_contribuyente` ENUM('PRIMERA_CATEGORIA','SEGUNDA_CATEGORIA','EXENTO','EXTRANJERO') DEFAULT 'PRIMERA_CATEGORIA',
  `retencion_impuestos` TINYINT(1) DEFAULT 0,
  `certificado_tributario` VARCHAR(255) DEFAULT NULL,
  `direccion_principal` VARCHAR(255) DEFAULT NULL,
  `ciudad` VARCHAR(100) DEFAULT NULL,
  `region` VARCHAR(100) DEFAULT NULL,
  `pais` VARCHAR(100) DEFAULT 'Chile',
  `codigo_postal` VARCHAR(20) DEFAULT NULL,
  `telefono` VARCHAR(50) DEFAULT NULL,
  `email` VARCHAR(150) DEFAULT NULL,
  `sitio_web` VARCHAR(200) DEFAULT NULL,
  `datos_bancarios` TEXT COMMENT 'JSON con banco, cuenta, swift, etc',
  `certificaciones` TEXT COMMENT 'ISO, etc',
  `observaciones` TEXT,
  `estado` ENUM('ACTIVO','INACTIVO','SUSPENDIDO','BLOQUEADO') DEFAULT 'ACTIVO',
  `created_by` INT(11) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT(11) DEFAULT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_codigo` (`codigo`),
  KEY `idx_rut` (`rut`),
  KEY `idx_estado` (`estado`),
  KEY `idx_categoria` (`categoria`),
  KEY `idx_tipo_proveedor` (`tipo_proveedor`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: proveedores_contactos
CREATE TABLE IF NOT EXISTS `proveedores_contactos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `proveedor_id` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(100) DEFAULT NULL,
  `departamento` VARCHAR(100) DEFAULT NULL,
  `email` VARCHAR(150) DEFAULT NULL,
  `telefono` VARCHAR(50) DEFAULT NULL,
  `telefono_movil` VARCHAR(50) DEFAULT NULL,
  `telefono_directo` VARCHAR(50) DEFAULT NULL,
  `rol_contacto` ENUM('PRINCIPAL','COMERCIAL','TECNICO','ADMINISTRATIVO','FINANCIERO','LOGISTICA','CALIDAD','OTROS') DEFAULT 'OTROS',
  `es_principal` TINYINT(1) DEFAULT 0,
  `recibe_ordenes_compra` TINYINT(1) DEFAULT 0,
  `recibe_notificaciones` TINYINT(1) DEFAULT 1,
  `idioma_preferido` VARCHAR(50) DEFAULT 'Español',
  `observaciones` TEXT,
  `estado` ENUM('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `created_by` INT(11) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT(11) DEFAULT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_proveedor_id` (`proveedor_id`),
  KEY `idx_estado` (`estado`),
  KEY `idx_es_principal` (`es_principal`),
  KEY `idx_email` (`email`),
  CONSTRAINT `fk_contactos_proveedor` FOREIGN KEY (`proveedor_id`) REFERENCES `proveedores` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: proveedores_contratos
CREATE TABLE IF NOT EXISTS `proveedores_contratos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `proveedor_id` INT(11) NOT NULL,
  `numero_contrato` VARCHAR(50) NOT NULL UNIQUE,
  `tipo_contrato` ENUM('SUMINISTRO','SERVICIOS','MARCO','CONSIGNACION','ARRENDAMIENTO','EXCLUSIVIDAD','OTROS') DEFAULT 'SUMINISTRO',
  `descripcion` TEXT,
  `objeto_contrato` TEXT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE DEFAULT NULL,
  `duracion_meses` INT(11) DEFAULT NULL,
  `monto_total` DECIMAL(15,2) DEFAULT 0.00,
  `moneda` VARCHAR(10) DEFAULT 'CLP',
  `forma_pago` VARCHAR(100) DEFAULT NULL,
  `condiciones_pago` TEXT,
  `penalidades` TEXT,
  `garantias_requeridas` TEXT,
  `clausulas_especiales` TEXT,
  `renovacion_automatica` TINYINT(1) DEFAULT 0,
  `dias_preaviso_renovacion` INT(11) DEFAULT 60,
  `estado_contrato` ENUM('BORRADOR','VIGENTE','SUSPENDIDO','VENCIDO','CANCELADO','RENOVADO') DEFAULT 'BORRADOR',
  `responsable_empresa` VARCHAR(100) DEFAULT NULL,
  `responsable_proveedor` VARCHAR(100) DEFAULT NULL,
  `archivo_contrato` VARCHAR(255) DEFAULT NULL,
  `observaciones` TEXT,
  `created_by` INT(11) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT(11) DEFAULT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_proveedor_id` (`proveedor_id`),
  KEY `idx_numero_contrato` (`numero_contrato`),
  KEY `idx_estado_contrato` (`estado_contrato`),
  KEY `idx_fecha_inicio` (`fecha_inicio`),
  KEY `idx_fecha_fin` (`fecha_fin`),
  CONSTRAINT `fk_contratos_proveedor` FOREIGN KEY (`proveedor_id`) REFERENCES `proveedores` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: proveedores_evaluaciones
CREATE TABLE IF NOT EXISTS `proveedores_evaluaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `proveedor_id` INT(11) NOT NULL,
  `periodo_evaluacion` VARCHAR(50) NOT NULL,
  `fecha_evaluacion` DATE NOT NULL,
  `evaluador` VARCHAR(100) DEFAULT NULL,
  `criterio_calidad` DECIMAL(3,2) DEFAULT 0.00 COMMENT 'Puntuación 0-10',
  `criterio_entrega` DECIMAL(3,2) DEFAULT 0.00 COMMENT 'Cumplimiento plazos 0-10',
  `criterio_precio` DECIMAL(3,2) DEFAULT 0.00 COMMENT 'Competitividad 0-10',
  `criterio_servicio` DECIMAL(3,2) DEFAULT 0.00 COMMENT 'Atención 0-10',
  `criterio_documentacion` DECIMAL(3,2) DEFAULT 0.00 COMMENT 'Facturación/docs 0-10',
  `criterio_innovacion` DECIMAL(3,2) DEFAULT 0.00 COMMENT 'Mejora continua 0-10',
  `calificacion_total` DECIMAL(3,2) DEFAULT 0.00 COMMENT 'Promedio ponderado',
  `nivel_desempeno` ENUM('EXCELENTE','BUENO','ACEPTABLE','DEFICIENTE','INACEPTABLE') DEFAULT 'ACEPTABLE',
  `incidencias` TEXT,
  `acciones_correctivas` TEXT,
  `plan_mejora` TEXT,
  `observaciones` TEXT,
  `aprobado_por` VARCHAR(100) DEFAULT NULL,
  `fecha_aprobacion` DATE DEFAULT NULL,
  `estado` ENUM('BORRADOR','APROBADA','RECHAZADA') DEFAULT 'BORRADOR',
  `created_by` INT(11) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT(11) DEFAULT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_proveedor_id` (`proveedor_id`),
  KEY `idx_fecha_evaluacion` (`fecha_evaluacion`),
  KEY `idx_nivel_desempeno` (`nivel_desempeno`),
  KEY `idx_estado` (`estado`),
  CONSTRAINT `fk_evaluaciones_proveedor` FOREIGN KEY (`proveedor_id`) REFERENCES `proveedores` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: proveedores_condiciones (condiciones comerciales y descuentos)
CREATE TABLE IF NOT EXISTS `proveedores_condiciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `proveedor_id` INT(11) NOT NULL,
  `codigo_condicion` VARCHAR(50) NOT NULL UNIQUE,
  `nombre_condicion` VARCHAR(200) NOT NULL,
  `descripcion` TEXT,
  `tipo_condicion` ENUM('DESCUENTO_VOLUMEN','DESCUENTO_PRONTO_PAGO','PRECIO_ESPECIAL','RAPPEL','BONIFICACION','CREDITO','OTROS') DEFAULT 'DESCUENTO_VOLUMEN',
  `tipo_descuento` ENUM('PORCENTAJE','MONTO_FIJO','PRECIO_ESPECIAL') DEFAULT 'PORCENTAJE',
  `valor_descuento` DECIMAL(10,2) DEFAULT 0.00,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE DEFAULT NULL,
  `productos_aplicables` TEXT COMMENT 'JSON o lista de SKUs',
  `categorias_aplicables` TEXT COMMENT 'JSON o lista de categorías',
  `cantidad_minima` INT(11) DEFAULT NULL,
  `monto_minimo` DECIMAL(15,2) DEFAULT NULL,
  `frecuencia` ENUM('DIARIA','SEMANAL','QUINCENAL','MENSUAL','TRIMESTRAL','SEMESTRAL','ANUAL','SIN_RESTRICCION') DEFAULT 'SIN_RESTRICCION',
  `acumulable` TINYINT(1) DEFAULT 0,
  `requiere_autorizacion` TINYINT(1) DEFAULT 0,
  `prioridad` INT(11) DEFAULT 1,
  `condiciones_aplicacion` TEXT,
  `estado` ENUM('BORRADOR','ACTIVO','SUSPENDIDO','VENCIDO','CANCELADO') DEFAULT 'BORRADOR',
  `observaciones` TEXT,
  `created_by` INT(11) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT(11) DEFAULT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_proveedor_id` (`proveedor_id`),
  KEY `idx_codigo_condicion` (`codigo_condicion`),
  KEY `idx_estado` (`estado`),
  KEY `idx_tipo_condicion` (`tipo_condicion`),
  CONSTRAINT `fk_condiciones_proveedor` FOREIGN KEY (`proveedor_id`) REFERENCES `proveedores` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Indices adicionales para optimización
CREATE INDEX idx_proveedores_razon_social ON proveedores(razon_social);
CREATE INDEX idx_proveedores_calificacion ON proveedores(calificacion);
CREATE INDEX idx_contactos_rol ON proveedores_contactos(rol_contacto);
CREATE INDEX idx_evaluaciones_calificacion ON proveedores_evaluaciones(calificacion_total);
