-- =====================================================
-- CONECTA ERP v2.0.0 - SCHEMA COMPLETO PARTE 2
-- Módulos: SD, MM, PP, HCM, SCM, CRM, LOY, BI, ADM
-- Incluye: Previred, SII, Relojes Control, Multi-currency
-- =====================================================

-- =====================================================
-- MÓDULO 5: VENTAS (SD) - 9 Submódulos
-- Sistema de Ventas SUPER COMPLETO con Multi-currency y Caja
-- =====================================================

-- Clientes (mejorado del módulo de entidades)
CREATE TABLE IF NOT EXISTS `sd_customers` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `customer_code` VARCHAR(50) NOT NULL,
  `customer_type` ENUM('individual', 'business') NOT NULL,
  `tax_id` VARCHAR(50),
  `business_name` VARCHAR(255),
  `first_name` VARCHAR(100),
  `last_name` VARCHAR(100),
  `email` VARCHAR(150),
  `phone` VARCHAR(50),
  `mobile` VARCHAR(50),
  `website` VARCHAR(255),
  `industry` VARCHAR(100),
  `address` TEXT,
  `city` VARCHAR(100),
  `state_province` VARCHAR(100),
  `postal_code` VARCHAR(20),
  `country_code` VARCHAR(3) DEFAULT 'CL',
  `billing_address` TEXT,
  `shipping_address` TEXT,
  `credit_limit` DECIMAL(18,2) DEFAULT 0.00,
  `credit_limit_currency` VARCHAR(3) DEFAULT 'CLP',
  `current_balance` DECIMAL(18,2) DEFAULT 0.00,
  `payment_terms_days` INT(11) DEFAULT 30,
  `discount_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `price_list_id` INT(11) UNSIGNED,
  `sales_rep_id` INT(11) UNSIGNED,
  `customer_since` DATE,
  `credit_status` ENUM('good', 'warning', 'blocked', 'legal') DEFAULT 'good',
  `loyalty_points` INT(11) DEFAULT 0,
  `loyalty_tier` ENUM('bronze', 'silver', 'gold', 'platinum') DEFAULT 'bronze',
  `is_active` TINYINT(1) DEFAULT 1,
  `notes` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `company_customer_code` (`company_id`, `customer_code`),
  INDEX `idx_tax_id` (`tax_id`),
  INDEX `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listas de Precios
CREATE TABLE IF NOT EXISTS `sd_price_lists` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `price_list_code` VARCHAR(50) NOT NULL,
  `price_list_name` VARCHAR(200) NOT NULL,
  `currency` VARCHAR(3) DEFAULT 'CLP',
  `is_default` TINYINT(1) DEFAULT 0,
  `valid_from` DATE,
  `valid_to` DATE,
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `company_price_list_code` (`company_id`, `price_list_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Precios por Producto
CREATE TABLE IF NOT EXISTS `sd_product_prices` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `price_list_id` INT(11) UNSIGNED NOT NULL,
  `product_id` INT(11) UNSIGNED NOT NULL,
  `price` DECIMAL(18,4) NOT NULL,
  `min_quantity` DECIMAL(10,2) DEFAULT 1.00,
  `discount_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `valid_from` DATE,
  `valid_to` DATE,
  `is_active` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`price_list_id`) REFERENCES `sd_price_lists`(`id`) ON DELETE CASCADE,
  INDEX `idx_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Cotizaciones
CREATE TABLE IF NOT EXISTS `sd_quotations` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `quotation_number` VARCHAR(50) NOT NULL,
  `quotation_date` DATE NOT NULL,
  `valid_until` DATE NOT NULL,
  `customer_id` INT(11) UNSIGNED NOT NULL,
  `contact_person` VARCHAR(150),
  `contact_email` VARCHAR(150),
  `contact_phone` VARCHAR(50),
  `sales_rep_id` INT(11) UNSIGNED,
  `currency` VARCHAR(3) DEFAULT 'CLP',
  `exchange_rate` DECIMAL(10,6) DEFAULT 1.000000,
  `subtotal` DECIMAL(18,2) NOT NULL,
  `discount_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `discount_amount` DECIMAL(18,2) DEFAULT 0.00,
  `tax_amount` DECIMAL(18,2) NOT NULL,
  `shipping_cost` DECIMAL(18,2) DEFAULT 0.00,
  `total_amount` DECIMAL(18,2) NOT NULL,
  `payment_terms` VARCHAR(200),
  `delivery_terms` VARCHAR(200),
  `notes` TEXT,
  `internal_notes` TEXT,
  `status` ENUM('draft', 'sent', 'viewed', 'accepted', 'rejected', 'expired', 'converted') DEFAULT 'draft',
  `sent_at` DATETIME,
  `viewed_at` DATETIME,
  `accepted_at` DATETIME,
  `converted_to_order_id` INT(11) UNSIGNED,
  `created_by` INT(11) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`customer_id`) REFERENCES `sd_customers`(`id`),
  UNIQUE KEY `company_quotation_number` (`company_id`, `quotation_number`),
  INDEX `idx_status` (`status`),
  INDEX `idx_date` (`quotation_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Líneas de Cotización
CREATE TABLE IF NOT EXISTS `sd_quotation_lines` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `quotation_id` INT(11) UNSIGNED NOT NULL,
  `line_number` INT(11) NOT NULL,
  `product_id` INT(11) UNSIGNED NOT NULL,
  `product_code` VARCHAR(50) NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `quantity` DECIMAL(10,2) NOT NULL,
  `unit_of_measure` VARCHAR(20) NOT NULL,
  `unit_price` DECIMAL(18,4) NOT NULL,
  `discount_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `discount_amount` DECIMAL(18,2) DEFAULT 0.00,
  `tax_percentage` DECIMAL(5,2) DEFAULT 19.00,
  `tax_amount` DECIMAL(18,2) NOT NULL,
  `line_total` DECIMAL(18,2) NOT NULL,
  `notes` TEXT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`quotation_id`) REFERENCES `sd_quotations`(`id`) ON DELETE CASCADE,
  INDEX `idx_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Pedidos de Venta
CREATE TABLE IF NOT EXISTS `sd_sales_orders` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `order_number` VARCHAR(50) NOT NULL,
  `order_date` DATE NOT NULL,
  `customer_id` INT(11) UNSIGNED NOT NULL,
  `quotation_id` INT(11) UNSIGNED,
  `customer_po_number` VARCHAR(50),
  `sales_rep_id` INT(11) UNSIGNED,
  `currency` VARCHAR(3) DEFAULT 'CLP',
  `exchange_rate` DECIMAL(10,6) DEFAULT 1.000000,
  `subtotal` DECIMAL(18,2) NOT NULL,
  `discount_amount` DECIMAL(18,2) DEFAULT 0.00,
  `tax_amount` DECIMAL(18,2) NOT NULL,
  `shipping_cost` DECIMAL(18,2) DEFAULT 0.00,
  `total_amount` DECIMAL(18,2) NOT NULL,
  `payment_terms` VARCHAR(200),
  `shipping_method` VARCHAR(100),
  `requested_delivery_date` DATE,
  `confirmed_delivery_date` DATE,
  `shipping_address` TEXT,
  `billing_address` TEXT,
  `status` ENUM('pending', 'confirmed', 'processing', 'partially_shipped', 'shipped', 'delivered', 'cancelled', 'on_hold') DEFAULT 'pending',
  `payment_status` ENUM('unpaid', 'partially_paid', 'paid', 'refunded') DEFAULT 'unpaid',
  `fulfillment_status` ENUM('unfulfilled', 'partially_fulfilled', 'fulfilled') DEFAULT 'unfulfilled',
  `notes` TEXT,
  `internal_notes` TEXT,
  `created_by` INT(11) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`customer_id`) REFERENCES `sd_customers`(`id`),
  FOREIGN KEY (`quotation_id`) REFERENCES `sd_quotations`(`id`),
  UNIQUE KEY `company_order_number` (`company_id`, `order_number`),
  INDEX `idx_status` (`status`),
  INDEX `idx_date` (`order_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Líneas de Pedido
CREATE TABLE IF NOT EXISTS `sd_sales_order_lines` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) UNSIGNED NOT NULL,
  `line_number` INT(11) NOT NULL,
  `product_id` INT(11) UNSIGNED NOT NULL,
  `product_code` VARCHAR(50) NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `quantity_ordered` DECIMAL(10,2) NOT NULL,
  `quantity_shipped` DECIMAL(10,2) DEFAULT 0.00,
  `quantity_invoiced` DECIMAL(10,2) DEFAULT 0.00,
  `quantity_returned` DECIMAL(10,2) DEFAULT 0.00,
  `unit_of_measure` VARCHAR(20) NOT NULL,
  `unit_price` DECIMAL(18,4) NOT NULL,
  `discount_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `discount_amount` DECIMAL(18,2) DEFAULT 0.00,
  `tax_percentage` DECIMAL(5,2) DEFAULT 19.00,
  `tax_amount` DECIMAL(18,2) NOT NULL,
  `line_total` DECIMAL(18,2) NOT NULL,
  `warehouse_id` INT(11) UNSIGNED,
  `requested_delivery_date` DATE,
  `notes` TEXT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`order_id`) REFERENCES `sd_sales_orders`(`id`) ON DELETE CASCADE,
  INDEX `idx_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Facturas de Venta
CREATE TABLE IF NOT EXISTS `sd_invoices` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `invoice_number` VARCHAR(50) NOT NULL,
  `invoice_type` ENUM('invoice', 'credit_note', 'debit_note', 'proforma') DEFAULT 'invoice',
  `invoice_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `customer_id` INT(11) UNSIGNED NOT NULL,
  `order_id` INT(11) UNSIGNED,
  `currency` VARCHAR(3) DEFAULT 'CLP',
  `exchange_rate` DECIMAL(10,6) DEFAULT 1.000000,
  `subtotal` DECIMAL(18,2) NOT NULL,
  `discount_amount` DECIMAL(18,2) DEFAULT 0.00,
  `tax_amount` DECIMAL(18,2) NOT NULL,
  `total_amount` DECIMAL(18,2) NOT NULL,
  `paid_amount` DECIMAL(18,2) DEFAULT 0.00,
  `balance` DECIMAL(18,2) NOT NULL,
  `payment_terms` VARCHAR(200),
  `status` ENUM('draft', 'issued', 'sent', 'partially_paid', 'paid', 'overdue', 'cancelled', 'refunded') DEFAULT 'draft',
  `payment_status` ENUM('unpaid', 'partially_paid', 'paid', 'refunded') DEFAULT 'unpaid',
  `dte_type` VARCHAR(10),
  `dte_folio` VARCHAR(50),
  `dte_xml` TEXT,
  `dte_pdf_url` VARCHAR(255),
  `sii_status` ENUM('not_sent', 'sent', 'accepted', 'rejected', 'cancelled') DEFAULT 'not_sent',
  `sii_track_id` VARCHAR(100),
  `sii_response` TEXT,
  `billing_address` TEXT,
  `notes` TEXT,
  `created_by` INT(11) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`customer_id`) REFERENCES `sd_customers`(`id`),
  FOREIGN KEY (`order_id`) REFERENCES `sd_sales_orders`(`id`),
  UNIQUE KEY `company_invoice_number` (`company_id`, `invoice_number`),
  INDEX `idx_status` (`status`),
  INDEX `idx_due_date` (`due_date`),
  INDEX `idx_dte_folio` (`dte_folio`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Líneas de Factura
CREATE TABLE IF NOT EXISTS `sd_invoice_lines` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoice_id` INT(11) UNSIGNED NOT NULL,
  `line_number` INT(11) NOT NULL,
  `product_id` INT(11) UNSIGNED NOT NULL,
  `product_code` VARCHAR(50) NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `quantity` DECIMAL(10,2) NOT NULL,
  `unit_of_measure` VARCHAR(20) NOT NULL,
  `unit_price` DECIMAL(18,4) NOT NULL,
  `discount_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `discount_amount` DECIMAL(18,2) DEFAULT 0.00,
  `tax_percentage` DECIMAL(5,2) DEFAULT 19.00,
  `tax_amount` DECIMAL(18,2) NOT NULL,
  `line_total` DECIMAL(18,2) NOT NULL,
  `order_line_id` INT(11) UNSIGNED,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`invoice_id`) REFERENCES `sd_invoices`(`id`) ON DELETE CASCADE,
  INDEX `idx_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Cajas (POS Terminals)
CREATE TABLE IF NOT EXISTS `sd_pos_terminals` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `terminal_code` VARCHAR(50) NOT NULL,
  `terminal_name` VARCHAR(200) NOT NULL,
  `location` VARCHAR(200),
  `warehouse_id` INT(11) UNSIGNED,
  `default_currency` VARCHAR(3) DEFAULT 'CLP',
  `accepts_multiple_currencies` TINYINT(1) DEFAULT 1,
  `accepted_currencies` JSON,
  `cash_drawer_opening_balance` DECIMAL(18,2) DEFAULT 0.00,
  `current_balance` DECIMAL(18,2) DEFAULT 0.00,
  `is_active` TINYINT(1) DEFAULT 1,
  `printer_name` VARCHAR(100),
  `receipt_header` TEXT,
  `receipt_footer` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `company_terminal_code` (`company_id`, `terminal_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Sesiones de Caja
CREATE TABLE IF NOT EXISTS `sd_pos_sessions` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `terminal_id` INT(11) UNSIGNED NOT NULL,
  `session_number` VARCHAR(50) NOT NULL,
  `opened_by` INT(11) UNSIGNED NOT NULL,
  `opened_at` DATETIME NOT NULL,
  `opening_balance` DECIMAL(18,2) NOT NULL,
  `opening_balance_currency` VARCHAR(3) DEFAULT 'CLP',
  `closed_by` INT(11) UNSIGNED,
  `closed_at` DATETIME,
  `expected_cash` DECIMAL(18,2),
  `actual_cash` DECIMAL(18,2),
  `cash_difference` DECIMAL(18,2),
  `total_sales` DECIMAL(18,2) DEFAULT 0.00,
  `total_refunds` DECIMAL(18,2) DEFAULT 0.00,
  `total_cash` DECIMAL(18,2) DEFAULT 0.00,
  `total_card` DECIMAL(18,2) DEFAULT 0.00,
  `total_transfer` DECIMAL(18,2) DEFAULT 0.00,
  `total_mobile` DECIMAL(18,2) DEFAULT 0.00,
  `total_other` DECIMAL(18,2) DEFAULT 0.00,
  `transaction_count` INT(11) DEFAULT 0,
  `status` ENUM('open', 'closed', 'reconciled') DEFAULT 'open',
  `notes` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`terminal_id`) REFERENCES `sd_pos_terminals`(`id`) ON DELETE CASCADE,
  INDEX `idx_status` (`status`),
  INDEX `idx_opened_at` (`opened_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Transacciones POS
CREATE TABLE IF NOT EXISTS `sd_pos_transactions` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `session_id` INT(11) UNSIGNED NOT NULL,
  `transaction_number` VARCHAR(50) NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  `customer_id` INT(11) UNSIGNED,
  `customer_name` VARCHAR(255),
  `customer_tax_id` VARCHAR(50),
  `cashier_id` INT(11) UNSIGNED NOT NULL,
  `currency` VARCHAR(3) DEFAULT 'CLP',
  `exchange_rate` DECIMAL(10,6) DEFAULT 1.000000,
  `subtotal` DECIMAL(18,2) NOT NULL,
  `discount_amount` DECIMAL(18,2) DEFAULT 0.00,
  `tax_amount` DECIMAL(18,2) NOT NULL,
  `total_amount` DECIMAL(18,2) NOT NULL,
  `total_paid` DECIMAL(18,2) NOT NULL,
  `change_amount` DECIMAL(18,2) DEFAULT 0.00,
  `status` ENUM('completed', 'cancelled', 'refunded', 'partially_refunded') DEFAULT 'completed',
  `invoice_id` INT(11) UNSIGNED,
  `dte_type` VARCHAR(10),
  `dte_folio` VARCHAR(50),
  `notes` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`session_id`) REFERENCES `sd_pos_sessions`(`id`),
  FOREIGN KEY (`customer_id`) REFERENCES `sd_customers`(`id`),
  UNIQUE KEY `company_transaction_number` (`company_id`, `transaction_number`),
  INDEX `idx_date` (`transaction_date`),
  INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Líneas de Transacción POS
CREATE TABLE IF NOT EXISTS `sd_pos_transaction_lines` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `transaction_id` INT(11) UNSIGNED NOT NULL,
  `line_number` INT(11) NOT NULL,
  `product_id` INT(11) UNSIGNED NOT NULL,
  `product_code` VARCHAR(50) NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `quantity` DECIMAL(10,2) NOT NULL,
  `unit_price` DECIMAL(18,4) NOT NULL,
  `discount_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `discount_amount` DECIMAL(18,2) DEFAULT 0.00,
  `tax_percentage` DECIMAL(5,2) DEFAULT 19.00,
  `tax_amount` DECIMAL(18,2) NOT NULL,
  `line_total` DECIMAL(18,2) NOT NULL,
  `cost_price` DECIMAL(18,4),
  `profit_margin` DECIMAL(18,2),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`transaction_id`) REFERENCES `sd_pos_transactions`(`id`) ON DELETE CASCADE,
  INDEX `idx_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Pagos de Transacciones (Multi-currency y Multi-método)
CREATE TABLE IF NOT EXISTS `sd_pos_transaction_payments` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `transaction_id` INT(11) UNSIGNED NOT NULL,
  `payment_number` INT(11) NOT NULL,
  `payment_method` ENUM('cash', 'card_credit', 'card_debit', 'transfer', 'check', 'mobile_payment', 'gift_card', 'loyalty_points', 'other') NOT NULL,
  `amount` DECIMAL(18,2) NOT NULL,
  `currency` VARCHAR(3) NOT NULL,
  `exchange_rate` DECIMAL(10,6) DEFAULT 1.000000,
  `amount_in_base_currency` DECIMAL(18,2) NOT NULL,
  `card_type` VARCHAR(50),
  `card_last_4` VARCHAR(4),
  `authorization_code` VARCHAR(100),
  `reference_number` VARCHAR(100),
  `bank_name` VARCHAR(100),
  `account_number` VARCHAR(50),
  `notes` TEXT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`transaction_id`) REFERENCES `sd_pos_transactions`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Devoluciones
CREATE TABLE IF NOT EXISTS `sd_returns` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `return_number` VARCHAR(50) NOT NULL,
  `return_date` DATE NOT NULL,
  `customer_id` INT(11) UNSIGNED NOT NULL,
  `original_invoice_id` INT(11) UNSIGNED,
  `original_order_id` INT(11) UNSIGNED,
  `original_pos_transaction_id` INT(11) UNSIGNED,
  `return_reason` VARCHAR(200),
  `return_type` ENUM('full', 'partial') DEFAULT 'partial',
  `currency` VARCHAR(3) DEFAULT 'CLP',
  `subtotal` DECIMAL(18,2) NOT NULL,
  `tax_amount` DECIMAL(18,2) NOT NULL,
  `total_amount` DECIMAL(18,2) NOT NULL,
  `refund_method` ENUM('cash', 'credit_note', 'store_credit', 'original_payment_method') NOT NULL,
  `refund_status` ENUM('pending', 'approved', 'refunded', 'rejected') DEFAULT 'pending',
  `approved_by` INT(11) UNSIGNED,
  `approved_at` DATETIME,
  `credit_note_id` INT(11) UNSIGNED,
  `status` ENUM('pending', 'processing', 'completed', 'cancelled') DEFAULT 'pending',
  `notes` TEXT,
  `created_by` INT(11) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`customer_id`) REFERENCES `sd_customers`(`id`),
  FOREIGN KEY (`original_invoice_id`) REFERENCES `sd_invoices`(`id`),
  FOREIGN KEY (`original_order_id`) REFERENCES `sd_sales_orders`(`id`),
  FOREIGN KEY (`original_pos_transaction_id`) REFERENCES `sd_pos_transactions`(`id`),
  UNIQUE KEY `company_return_number` (`company_id`, `return_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Líneas de Devolución
CREATE TABLE IF NOT EXISTS `sd_return_lines` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `return_id` INT(11) UNSIGNED NOT NULL,
  `line_number` INT(11) NOT NULL,
  `product_id` INT(11) UNSIGNED NOT NULL,
  `product_code` VARCHAR(50) NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `quantity_returned` DECIMAL(10,2) NOT NULL,
  `unit_price` DECIMAL(18,4) NOT NULL,
  `tax_percentage` DECIMAL(5,2) DEFAULT 19.00,
  `tax_amount` DECIMAL(18,2) NOT NULL,
  `line_total` DECIMAL(18,2) NOT NULL,
  `return_to_inventory` TINYINT(1) DEFAULT 1,
  `warehouse_id` INT(11) UNSIGNED,
  `condition` ENUM('new', 'damaged', 'defective', 'opened') DEFAULT 'new',
  `notes` TEXT,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`return_id`) REFERENCES `sd_returns`(`id`) ON DELETE CASCADE,
  INDEX `idx_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Promociones y Descuentos
CREATE TABLE IF NOT EXISTS `sd_promotions` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `promotion_code` VARCHAR(50) NOT NULL,
  `promotion_name` VARCHAR(200) NOT NULL,
  `description` TEXT,
  `promotion_type` ENUM('percentage_discount', 'fixed_amount', 'buy_x_get_y', 'bundle', 'loyalty_points', 'free_shipping') NOT NULL,
  `discount_percentage` DECIMAL(5,2),
  `discount_amount` DECIMAL(18,2),
  `min_purchase_amount` DECIMAL(18,2),
  `max_discount_amount` DECIMAL(18,2),
  `buy_quantity` INT(11),
  `get_quantity` INT(11),
  `applicable_to` ENUM('all_products', 'specific_products', 'categories', 'customers') NOT NULL,
  `product_ids` JSON,
  `category_ids` JSON,
  `customer_ids` JSON,
  `customer_tiers` JSON,
  `valid_from` DATETIME NOT NULL,
  `valid_to` DATETIME NOT NULL,
  `usage_limit` INT(11),
  `usage_limit_per_customer` INT(11),
  `current_usage_count` INT(11) DEFAULT 0,
  `is_active` TINYINT(1) DEFAULT 1,
  `stackable` TINYINT(1) DEFAULT 0,
  `priority` INT(11) DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `company_promotion_code` (`company_id`, `promotion_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Uso de Promociones
CREATE TABLE IF NOT EXISTS `sd_promotion_usage` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `promotion_id` INT(11) UNSIGNED NOT NULL,
  `customer_id` INT(11) UNSIGNED,
  `order_id` INT(11) UNSIGNED,
  `invoice_id` INT(11) UNSIGNED,
  `pos_transaction_id` INT(11) UNSIGNED,
  `discount_amount` DECIMAL(18,2) NOT NULL,
  `used_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`promotion_id`) REFERENCES `sd_promotions`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`customer_id`) REFERENCES `sd_customers`(`id`),
  INDEX `idx_used_at` (`used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Análisis de Ventas
CREATE TABLE IF NOT EXISTS `sd_sales_analytics` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `analysis_date` DATE NOT NULL,
  `period_type` ENUM('daily', 'weekly', 'monthly', 'quarterly', 'yearly') NOT NULL,
  `total_sales` DECIMAL(18,2) NOT NULL,
  `total_cost` DECIMAL(18,2) NOT NULL,
  `gross_profit` DECIMAL(18,2) NOT NULL,
  `gross_margin_percentage` DECIMAL(5,2) NOT NULL,
  `total_orders` INT(11) NOT NULL,
  `total_invoices` INT(11) NOT NULL,
  `total_pos_transactions` INT(11) NOT NULL,
  `average_order_value` DECIMAL(18,2) NOT NULL,
  `total_customers` INT(11) NOT NULL,
  `new_customers` INT(11) NOT NULL,
  `returning_customers` INT(11) NOT NULL,
  `total_returns` DECIMAL(18,2) DEFAULT 0.00,
  `return_rate_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `sales_by_channel` JSON,
  `sales_by_category` JSON,
  `sales_by_product` JSON,
  `sales_by_sales_rep` JSON,
  `sales_by_region` JSON,
  `payment_methods_breakdown` JSON,
  `currency_breakdown` JSON,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `company_analysis_date_period` (`company_id`, `analysis_date`, `period_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Catálogo de Productos para Ventas
CREATE TABLE IF NOT EXISTS `sd_product_catalog` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `product_id` INT(11) UNSIGNED NOT NULL,
  `is_featured` TINYINT(1) DEFAULT 0,
  `is_new` TINYINT(1) DEFAULT 0,
  `is_best_seller` TINYINT(1) DEFAULT 0,
  `is_on_sale` TINYINT(1) DEFAULT 0,
  `display_order` INT(11) DEFAULT 0,
  `short_description` TEXT,
  `long_description` TEXT,
  `specifications` JSON,
  `features` JSON,
  `images` JSON,
  `video_url` VARCHAR(255),
  `meta_title` VARCHAR(200),
  `meta_description` TEXT,
  `meta_keywords` VARCHAR(255),
  `seo_url` VARCHAR(255),
  `is_published` TINYINT(1) DEFAULT 1,
  `published_at` DATETIME,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `company_product` (`company_id`, `product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- MÓDULO 6: MATERIALES (MM) - 8 Submódulos
-- =====================================================

-- Productos/Materiales
CREATE TABLE IF NOT EXISTS `mm_products` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `product_code` VARCHAR(50) NOT NULL,
  `barcode` VARCHAR(100),
  `product_name` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `product_type` ENUM('finished_good', 'raw_material', 'semi_finished', 'service', 'consumable', 'spare_part') NOT NULL,
  `category_id` INT(11) UNSIGNED,
  `subcategory_id` INT(11) UNSIGNED,
  `brand` VARCHAR(100),
  `model` VARCHAR(100),
  `unit_of_measure` VARCHAR(20) NOT NULL,
  `secondary_uom` VARCHAR(20),
  `conversion_factor` DECIMAL(10,4) DEFAULT 1.0000,
  `standard_cost` DECIMAL(18,4) NOT NULL,
  `average_cost` DECIMAL(18,4) NOT NULL,
  `last_purchase_cost` DECIMAL(18,4),
  `selling_price` DECIMAL(18,4) NOT NULL,
  `min_selling_price` DECIMAL(18,4),
  `weight` DECIMAL(10,3),
  `weight_unit` VARCHAR(10),
  `volume` DECIMAL(10,3),
  `volume_unit` VARCHAR(10),
  `dimensions` VARCHAR(100),
  `hs_code` VARCHAR(20),
  `country_of_origin` VARCHAR(3),
  `manufacturer` VARCHAR(200),
  `supplier_id` INT(11) UNSIGNED,
  `lead_time_days` INT(11),
  `shelf_life_days` INT(11),
  `is_serialized` TINYINT(1) DEFAULT 0,
  `is_lot_controlled` TINYINT(1) DEFAULT 0,
  `is_perishable` TINYINT(1) DEFAULT 0,
  `is_hazardous` TINYINT(1) DEFAULT 0,
  `is_active` TINYINT(1) DEFAULT 1,
  `image_url` VARCHAR(255),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `company_product_code` (`company_id`, `product_code`),
  INDEX `idx_barcode` (`barcode`),
  INDEX `idx_category` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Categorías de Productos
CREATE TABLE IF NOT EXISTS `mm_product_categories` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `category_code` VARCHAR(50) NOT NULL,
  `category_name` VARCHAR(200) NOT NULL,
  `parent_id` INT(11) UNSIGNED,
  `level` INT(2) DEFAULT 1,
  `description` TEXT,
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`parent_id`) REFERENCES `mm_product_categories`(`id`) ON DELETE SET NULL,
  UNIQUE KEY `company_category_code` (`company_id`, `category_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Almacenes
CREATE TABLE IF NOT EXISTS `mm_warehouses` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `warehouse_code` VARCHAR(50) NOT NULL,
  `warehouse_name` VARCHAR(200) NOT NULL,
  `warehouse_type` ENUM('main', 'distribution', 'retail', 'consignment', 'transit', 'quarantine') NOT NULL,
  `address` TEXT,
  `city` VARCHAR(100),
  `state_province` VARCHAR(100),
  `postal_code` VARCHAR(20),
  `country_code` VARCHAR(3) DEFAULT 'CL',
  `phone` VARCHAR(50),
  `email` VARCHAR(150),
  `manager_id` INT(11) UNSIGNED,
  `total_capacity_sqm` DECIMAL(10,2),
  `used_capacity_sqm` DECIMAL(10,2),
  `capacity_utilization_percentage` DECIMAL(5,2),
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `company_warehouse_code` (`company_id`, `warehouse_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Ubicaciones dentro de Almacenes
CREATE TABLE IF NOT EXISTS `mm_warehouse_locations` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `warehouse_id` INT(11) UNSIGNED NOT NULL,
  `location_code` VARCHAR(50) NOT NULL,
  `location_name` VARCHAR(200),
  `location_type` ENUM('bin', 'shelf', 'rack', 'zone', 'floor', 'dock', 'staging') NOT NULL,
  `aisle` VARCHAR(20),
  `rack` VARCHAR(20),
  `level` VARCHAR(20),
  `bin` VARCHAR(20),
  `capacity` DECIMAL(10,2),
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`warehouse_id`) REFERENCES `mm_warehouses`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `warehouse_location_code` (`warehouse_id`, `location_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Inventario
CREATE TABLE IF NOT EXISTS `mm_inventory` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `product_id` INT(11) UNSIGNED NOT NULL,
  `warehouse_id` INT(11) UNSIGNED NOT NULL,
  `location_id` INT(11) UNSIGNED,
  `quantity_on_hand` DECIMAL(15,3) NOT NULL DEFAULT 0.000,
  `quantity_reserved` DECIMAL(15,3) NOT NULL DEFAULT 0.000,
  `quantity_available` DECIMAL(15,3) NOT NULL DEFAULT 0.000,
  `quantity_in_transit` DECIMAL(15,3) NOT NULL DEFAULT 0.000,
  `quantity_on_order` DECIMAL(15,3) NOT NULL DEFAULT 0.000,
  `min_stock_level` DECIMAL(15,3) DEFAULT 0.000,
  `max_stock_level` DECIMAL(15,3) DEFAULT 0.000,
  `reorder_point` DECIMAL(15,3) DEFAULT 0.000,
  `reorder_quantity` DECIMAL(15,3) DEFAULT 0.000,
  `safety_stock` DECIMAL(15,3) DEFAULT 0.000,
  `average_cost` DECIMAL(18,4) DEFAULT 0.0000,
  `total_value` DECIMAL(18,2) DEFAULT 0.00,
  `last_movement_date` DATETIME,
  `last_count_date` DATE,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `mm_products`(`id`),
  FOREIGN KEY (`warehouse_id`) REFERENCES `mm_warehouses`(`id`),
  FOREIGN KEY (`location_id`) REFERENCES `mm_warehouse_locations`(`id`),
  UNIQUE KEY `product_warehouse_location` (`product_id`, `warehouse_id`, `location_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Continue in next file (Part 3) due to length...
-- This is getting very long. Will continue with MM, PP, HCM, SCM, CRM, LOY, BI, ADM modules in Part 3.
